#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any, Dict, List, Set


PRIMITIVES: List[str] = [
    "adc",
    "fs",
    "gpio",
    "i2c",
    "pwm",
    "spi",
    "sys",
    "timer",
    "uart",
]


def discover_ports(root: Path) -> List[Dict[str, Any]]:
    ports_root = root / "basalt_hal" / "ports"
    out: List[Dict[str, Any]] = []
    for port_dir in sorted([p for p in ports_root.iterdir() if p.is_dir()]):
        files = {p.name for p in port_dir.glob("hal_*.c")}
        present = sorted([p for p in PRIMITIVES if f"hal_{p}.c" in files])
        missing = sorted([p for p in PRIMITIVES if f"hal_{p}.c" not in files])
        if len(present) == len(PRIMITIVES):
            status = "complete"
        elif len(present) == 0:
            status = "missing"
        else:
            status = "partial"
        out.append(
            {
                "port": port_dir.name,
                "status": status,
                "present_count": len(present),
                "missing_count": len(missing),
                "present": present,
                "missing": missing,
            }
        )
    return out


def write_csv(rows: List[Dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["port", "status"] + [f"has_{p}" for p in PRIMITIVES]
    with out_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            row = {"port": r["port"], "status": r["status"]}
            present_set: Set[str] = set(r["present"])
            for p in PRIMITIVES:
                row[f"has_{p}"] = "yes" if p in present_set else "no"
            w.writerow(row)


def write_json(rows: List[Dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    summary = {
        "port_count": len(rows),
        "primitive_count": len(PRIMITIVES),
        "status_counts": {
            "complete": sum(1 for r in rows if r["status"] == "complete"),
            "partial": sum(1 for r in rows if r["status"] == "partial"),
            "missing": sum(1 for r in rows if r["status"] == "missing"),
        },
        "ports_with_missing_primitives": [
            {"port": r["port"], "missing": r["missing"]}
            for r in rows
            if r["missing_count"] > 0
        ],
    }
    payload = {
        "version": "1.0.0",
        "generator": "tools/generate_hal_adapter_matrix.py",
        "primitives": PRIMITIVES,
        "summary": summary,
        "rows": rows,
    }
    out_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_md(rows: List[Dict[str, Any]], out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    complete = sum(1 for r in rows if r["status"] == "complete")
    partial = sum(1 for r in rows if r["status"] == "partial")
    missing = sum(1 for r in rows if r["status"] == "missing")
    lines: List[str] = []
    lines.append("# HAL Adapter Matrix v1")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_hal_adapter_matrix.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Ports discovered: {len(rows)}")
    lines.append(f"- HAL primitives tracked: {len(PRIMITIVES)}")
    lines.append(f"- Complete adapters: {complete}")
    lines.append(f"- Partial adapters: {partial}")
    lines.append(f"- Missing adapters: {missing}")
    lines.append("")
    lines.append("| Port | Status | Present | Missing |")
    lines.append("|---|---|---|---|")
    for r in rows:
        present = ", ".join(r["present"]) if r["present"] else "-"
        missing_list = ", ".join(r["missing"]) if r["missing"] else "-"
        lines.append(f"| {r['port']} | {r['status']} | {present} | {missing_list} |")
    lines.append("")
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate HAL adapter capability matrix artifacts.")
    ap.add_argument("--csv-out", default="docs/planning/HAL_ADAPTER_MATRIX.csv")
    ap.add_argument("--json-out", default="docs/planning/HAL_ADAPTER_MATRIX.json")
    ap.add_argument("--md-out", default="docs/planning/HAL_ADAPTER_MATRIX.md")
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    rows = discover_ports(root)
    rows.sort(key=lambda x: x["port"])

    csv_out = (root / args.csv_out).resolve()
    json_out = (root / args.json_out).resolve()
    md_out = (root / args.md_out).resolve()

    write_csv(rows, csv_out)
    write_json(rows, json_out)
    write_md(rows, md_out)

    print(f"[hal-matrix] ports: {len(rows)}")
    print(f"[hal-matrix] primitives: {len(PRIMITIVES)}")
    print(f"[hal-matrix] wrote: {csv_out}")
    print(f"[hal-matrix] wrote: {json_out}")
    print(f"[hal-matrix] wrote: {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
