#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Dict, List


REPRESENTATIVE_BOARDS: Dict[str, str] = {
    "atmega": "arduino_uno_r3",
    "atsam": "adafruit_circuit_playground_express",
    "avr": "mega2560",
    "esp32": "esp32-c3-supermini",
    "linux-sbc": "raspberry_pi_4b",
    "pic16": "curiosity_nano_pic16f13145",
    "renesas_ra": "arduino_uno_r4_wifi",
    "renesas_rx": "rx65n_envision_kit",
    "rp2040": "raspberry_pi_pico",
    "stm32": "nucleo_f401re",
}

REQUIRED_ARTIFACTS = [
    "basalt_config.h",
    "basalt.features.json",
    "sdkconfig.defaults",
    "basalt_config.json",
]


def run_case(root: Path, platform: str, board: str, out_root: Path) -> Dict[str, object]:
    outdir = out_root / platform / board
    outdir.mkdir(parents=True, exist_ok=True)
    log_path = outdir / "run.log"
    cmd = [
        "python3",
        "tools/configure.py",
        "--platform",
        platform,
        "--board",
        board,
        "--outdir",
        str(outdir),
    ]
    p = subprocess.run(cmd, cwd=root, capture_output=True, text=True)
    log_path.write_text((p.stdout or "") + ("\n" if p.stdout else "") + (p.stderr or ""), encoding="utf-8")
    artifacts = {name: (outdir / name).exists() for name in REQUIRED_ARTIFACTS}
    missing = [k for k, ok in artifacts.items() if not ok]
    return {
        "platform": platform,
        "board_dir": board,
        "command": " ".join(cmd),
        "exit_code": int(p.returncode),
        "artifacts": artifacts,
        "missing_artifacts": missing,
        "status": "PASS" if p.returncode == 0 and not missing else "FAIL",
        "log_path": str(log_path.relative_to(root)),
    }


def write_json(path: Path, payload: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_md(path: Path, rows: List[Dict[str, object]], out_root: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    pass_count = sum(1 for r in rows if r["status"] == "PASS")
    fail_count = len(rows) - pass_count
    lines: List[str] = []
    lines.append("# Cross-Platform Generation Parity Baseline")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_generation_parity_baseline.py`.")
    lines.append("")
    lines.append(f"- Platforms covered: {len(rows)}")
    lines.append(f"- PASS: {pass_count}")
    lines.append(f"- FAIL: {fail_count}")
    lines.append(f"- Artifact root: `{out_root}`")
    lines.append("")
    lines.append("| Platform | Representative Board | Status | Missing Artifacts | Log |")
    lines.append("|---|---|---|---|---|")
    for r in rows:
        miss = ", ".join(r["missing_artifacts"]) if r["missing_artifacts"] else "-"
        lines.append(
            f"| {r['platform']} | {r['board_dir']} | {r['status']} | {miss} | `{r['log_path']}` |"
        )
    lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate cross-platform configure parity baseline artifacts.")
    ap.add_argument("--out-json", default="docs/planning/GENERATION_PARITY_BASELINE.json", help="JSON output path")
    ap.add_argument("--out-md", default="docs/planning/GENERATION_PARITY_BASELINE.md", help="Markdown output path")
    ap.add_argument(
        "--artifact-root",
        default="tmp/generation_parity_baseline",
        help="Output root for per-platform configure artifacts/logs",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    out_json = (root / args.out_json).resolve()
    out_md = (root / args.out_md).resolve()
    artifact_root = (root / args.artifact_root).resolve()

    rows: List[Dict[str, object]] = []
    for platform in sorted(REPRESENTATIVE_BOARDS.keys()):
        rows.append(run_case(root, platform, REPRESENTATIVE_BOARDS[platform], artifact_root))

    payload = {
        "version": "1.0.0",
        "representative_boards": REPRESENTATIVE_BOARDS,
        "required_artifacts": REQUIRED_ARTIFACTS,
        "rows": rows,
        "summary": {
            "platform_count": len(rows),
            "pass_count": sum(1 for r in rows if r["status"] == "PASS"),
            "fail_count": sum(1 for r in rows if r["status"] != "PASS"),
        },
    }
    write_json(out_json, payload)
    write_md(out_md, rows, artifact_root.relative_to(root))

    print(f"[parity] wrote: {out_json}")
    print(f"[parity] wrote: {out_md}")
    print(f"[parity] artifact root: {artifact_root}")
    if payload["summary"]["fail_count"] > 0:
        print(f"[parity] failures: {payload['summary']['fail_count']}")
        return 1
    print("[parity] all representative platforms passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
