#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Set


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_boards(root: Path) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for board_json in sorted((root / "boards").rglob("board.json")):
        data = read_json(board_json)
        out.append(
            {
                "board_id": str(data.get("id") or board_json.parent.name),
                "platform": str(data.get("platform") or ""),
                "manufacturer": str(data.get("manufacturer") or "Unknown"),
                "capabilities": {str(x).strip() for x in (data.get("capabilities") or []) if str(x).strip()},
                "path": str(board_json.relative_to(root)),
            }
        )
    return out


def load_eeprom_contract(root: Path) -> Dict[str, Any]:
    mod = read_json(root / "modules" / "eeprom" / "module.json")
    return {
        "platforms": sorted([str(x).strip() for x in (mod.get("platforms") or []) if str(x).strip()]),
        "notes": list(mod.get("notes") or []),
    }


def build_report(boards: List[Dict[str, Any]], contract: Dict[str, Any]) -> Dict[str, Any]:
    supported_platforms: Set[str] = set(contract["platforms"])

    eeprom_enabled: List[Dict[str, Any]] = []
    missing_eeprom_intentional: List[Dict[str, Any]] = []
    eeprom_enabled_out_of_scope: List[Dict[str, Any]] = []

    for b in boards:
        has_eeprom = "eeprom" in b["capabilities"]
        row = {
            "board_id": b["board_id"],
            "platform": b["platform"],
            "manufacturer": b["manufacturer"],
        }
        if has_eeprom:
            eeprom_enabled.append(row)
            if b["platform"] not in supported_platforms:
                eeprom_enabled_out_of_scope.append(row)
        else:
            missing_eeprom_intentional.append(row)

    actionable_total = len(eeprom_enabled_out_of_scope)
    return {
        "version": "1.0.0",
        "policy": {
            "intentional_boundary": "Missing `eeprom` capability is intentional by default; EEPROM support is explicit board-level opt-in.",
            "actionable_boundary": "`eeprom` capability declared on a board whose platform is outside module/eeprom platform scope.",
        },
        "eeprom_module_contract": contract,
        "summary": {
            "board_count": len(boards),
            "eeprom_enabled_count": len(eeprom_enabled),
            "eeprom_missing_intentional_count": len(missing_eeprom_intentional),
            "actionable_total": actionable_total,
            "eeprom_enabled_by_platform": dict(sorted(Counter(x["platform"] for x in eeprom_enabled).items())),
            "eeprom_missing_by_platform": dict(sorted(Counter(x["platform"] for x in missing_eeprom_intentional).items())),
        },
        "lists": {
            "eeprom_enabled": sorted(eeprom_enabled, key=lambda x: (x["platform"], x["board_id"])),
            "eeprom_missing_intentional": sorted(
                missing_eeprom_intentional, key=lambda x: (x["platform"], x["board_id"])
            ),
            "eeprom_enabled_out_of_scope_actionable": sorted(
                eeprom_enabled_out_of_scope, key=lambda x: (x["platform"], x["board_id"])
            ),
        },
    }


def write_md(report: Dict[str, Any], out_path: Path) -> None:
    s = report["summary"]
    lines: List[str] = []
    lines.append("# EEPROM Capability Posture Report v1")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_eeprom_posture_report.py`.")
    lines.append("")
    lines.append("## Policy Boundaries")
    lines.append("")
    lines.append(f"- Intentional: {report['policy']['intentional_boundary']}")
    lines.append(f"- Actionable: {report['policy']['actionable_boundary']}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Boards analyzed: {int(s['board_count'])}")
    lines.append(f"- Boards with `eeprom` capability: {int(s['eeprom_enabled_count'])}")
    lines.append(f"- Boards missing `eeprom` (intentional): {int(s['eeprom_missing_intentional_count'])}")
    lines.append(f"- Actionable total: {int(s['actionable_total'])}")
    lines.append("")
    lines.append("## EEPROM Module Contract")
    lines.append("")
    lines.append(f"- Supported platforms: {', '.join(report['eeprom_module_contract']['platforms'])}")
    notes = report["eeprom_module_contract"].get("notes") or []
    if notes:
        lines.append("- Module notes:")
        for n in notes:
            lines.append(f"  - {n}")
    lines.append("")

    actionable = report["lists"]["eeprom_enabled_out_of_scope_actionable"]
    if actionable:
        lines.append("## Actionable: EEPROM Enabled Outside Module Platform Scope")
        lines.append("")
        for row in actionable:
            lines.append(f"- {row['platform']}/{row['board_id']} ({row['manufacturer']})")
        lines.append("")

    lines.append("## Intentional Queue Snapshot: Missing EEPROM (Top 30)")
    lines.append("")
    for row in report["lists"]["eeprom_missing_intentional"][:30]:
        lines.append(f"- {row['platform']}/{row['board_id']} ({row['manufacturer']})")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate EEPROM capability posture report artifacts.")
    ap.add_argument("--json-out", default="docs/planning/EEPROM_CAPABILITY_POSTURE.json")
    ap.add_argument("--md-out", default="docs/planning/EEPROM_CAPABILITY_POSTURE.md")
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    report = build_report(load_boards(root), load_eeprom_contract(root))

    json_out = (root / args.json_out).resolve()
    md_out = (root / args.md_out).resolve()
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    write_md(report, md_out)

    print(f"[eeprom-posture] boards: {report['summary']['board_count']}")
    print(f"[eeprom-posture] eeprom-enabled: {report['summary']['eeprom_enabled_count']}")
    print(f"[eeprom-posture] actionable: {report['summary']['actionable_total']}")
    print(f"[eeprom-posture] wrote: {json_out}")
    print(f"[eeprom-posture] wrote: {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
