#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Set


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_boards(root: Path) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    for board_json in sorted((root / "boards").rglob("board.json")):
        data = read_json(board_json)
        out.append(
            {
                "board_id": str(data.get("id") or board_json.parent.name),
                "platform": str(data.get("platform") or ""),
                "manufacturer": str(data.get("manufacturer") or "Unknown"),
                "mcu": str(data.get("mcu") or ""),
                "capabilities": {str(x).strip() for x in (data.get("capabilities") or []) if str(x).strip()},
                "path": str(board_json.relative_to(root)),
            }
        )
    return out


def load_contract(root: Path) -> Dict[str, Any]:
    mod = read_json(root / "modules" / "psram" / "module.json")
    return {
        "platforms": sorted([str(x).strip() for x in (mod.get("platforms") or []) if str(x).strip()]),
        "notes": list(mod.get("notes") or []),
    }


def build_report(boards: List[Dict[str, Any]], contract: Dict[str, Any]) -> Dict[str, Any]:
    supported_platforms: Set[str] = set(contract["platforms"])
    enabled: List[Dict[str, Any]] = []
    missing_intentional: List[Dict[str, Any]] = []
    enabled_out_of_scope_actionable: List[Dict[str, Any]] = []

    for b in boards:
        has_psram = "psram" in b["capabilities"]
        row = {
            "board_id": b["board_id"],
            "platform": b["platform"],
            "manufacturer": b["manufacturer"],
            "mcu": b["mcu"],
        }
        if has_psram:
            enabled.append(row)
            if b["platform"] not in supported_platforms:
                enabled_out_of_scope_actionable.append(row)
        else:
            missing_intentional.append(row)

    return {
        "version": "1.0.0",
        "policy": {
            "intentional_boundary": "Missing `psram` is intentional unless board profile explicitly confirms physical PSRAM.",
            "actionable_boundary": "`psram` capability declared on a board platform outside module/psram platform scope.",
        },
        "psram_module_contract": contract,
        "summary": {
            "board_count": len(boards),
            "psram_enabled_count": len(enabled),
            "psram_missing_intentional_count": len(missing_intentional),
            "actionable_total": len(enabled_out_of_scope_actionable),
            "psram_enabled_by_platform": dict(sorted(Counter(x["platform"] for x in enabled).items())),
            "psram_missing_by_platform": dict(sorted(Counter(x["platform"] for x in missing_intentional).items())),
        },
        "lists": {
            "psram_enabled": sorted(enabled, key=lambda x: (x["platform"], x["board_id"])),
            "psram_missing_intentional": sorted(missing_intentional, key=lambda x: (x["platform"], x["board_id"])),
            "psram_enabled_out_of_scope_actionable": sorted(
                enabled_out_of_scope_actionable, key=lambda x: (x["platform"], x["board_id"])
            ),
        },
    }


def write_md(report: Dict[str, Any], out_path: Path) -> None:
    s = report["summary"]
    lines: List[str] = []
    lines.append("# PSRAM Capability Posture Report v1")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_psram_posture_report.py`.")
    lines.append("")
    lines.append("## Policy Boundaries")
    lines.append("")
    lines.append(f"- Intentional: {report['policy']['intentional_boundary']}")
    lines.append(f"- Actionable: {report['policy']['actionable_boundary']}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Boards analyzed: {int(s['board_count'])}")
    lines.append(f"- Boards with `psram` capability: {int(s['psram_enabled_count'])}")
    lines.append(f"- Boards missing `psram` (intentional): {int(s['psram_missing_intentional_count'])}")
    lines.append(f"- Actionable total: {int(s['actionable_total'])}")
    lines.append("")

    if report["lists"]["psram_enabled_out_of_scope_actionable"]:
        lines.append("## Actionable: PSRAM Enabled Outside Module Platform Scope")
        lines.append("")
        for row in report["lists"]["psram_enabled_out_of_scope_actionable"]:
            lines.append(f"- {row['platform']}/{row['board_id']} ({row['manufacturer']})")
        lines.append("")

    lines.append("## PSRAM Enabled Boards")
    lines.append("")
    for row in report["lists"]["psram_enabled"]:
        lines.append(f"- {row['platform']}/{row['board_id']} ({row['manufacturer']}, MCU: {row['mcu']})")
    lines.append("")

    lines.append("## Intentional Queue Snapshot: Missing PSRAM (Top 30)")
    lines.append("")
    for row in report["lists"]["psram_missing_intentional"][:30]:
        lines.append(f"- {row['platform']}/{row['board_id']} ({row['manufacturer']})")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate PSRAM capability posture report artifacts.")
    ap.add_argument("--json-out", default="docs/planning/PSRAM_CAPABILITY_POSTURE.json")
    ap.add_argument("--md-out", default="docs/planning/PSRAM_CAPABILITY_POSTURE.md")
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    report = build_report(load_boards(root), load_contract(root))
    json_out = (root / args.json_out).resolve()
    md_out = (root / args.md_out).resolve()
    json_out.parent.mkdir(parents=True, exist_ok=True)
    json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    write_md(report, md_out)

    print(f"[psram-posture] boards: {report['summary']['board_count']}")
    print(f"[psram-posture] psram-enabled: {report['summary']['psram_enabled_count']}")
    print(f"[psram-posture] actionable: {report['summary']['actionable_total']}")
    print(f"[psram-posture] wrote: {json_out}")
    print(f"[psram-posture] wrote: {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
