#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List


ENOSYS_RE = re.compile(r"\breturn\s+-ENOSYS\s*;")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def classify_adapter(source: str) -> Dict[str, Any]:
    enosys_count = len(ENOSYS_RE.findall(source))
    has_placeholder = "BasaltOS HAL placeholder translation unit." in source
    if has_placeholder:
        status = "contract_only"
    elif enosys_count == 0:
        status = "real"
    else:
        status = "real_with_optional_gaps"
    return {
        "status": status,
        "enosys_count": enosys_count,
        "placeholder_translation_unit": has_placeholder,
    }


def build_report(root: Path) -> Dict[str, Any]:
    ports_root = root / "basalt_hal" / "ports"
    per_port: List[Dict[str, Any]] = []

    for port_dir in sorted([p for p in ports_root.iterdir() if p.is_dir()]):
        adapters = []
        status_counts = Counter()
        total_enosys = 0

        for src in sorted(port_dir.glob("hal_*.c")):
            text = read_text(src)
            c = classify_adapter(text)
            status_counts[c["status"]] += 1
            total_enosys += int(c["enosys_count"])
            adapters.append(
                {
                    "adapter": src.stem,
                    "path": str(src.relative_to(root)),
                    **c,
                }
            )

        per_port.append(
            {
                "port": port_dir.name,
                "adapter_count": len(adapters),
                "status_counts": dict(status_counts),
                "total_enosys": total_enosys,
                "adapters": adapters,
            }
        )

    total_status = Counter()
    total_adapters = 0
    total_enosys = 0
    for row in per_port:
        total_adapters += int(row["adapter_count"])
        total_enosys += int(row["total_enosys"])
        for k, v in row["status_counts"].items():
            total_status[k] += int(v)

    return {
        "version": "1.0.0",
        "generator": "tools/generate_hal_maturity_report.py",
        "ports": per_port,
        "summary": {
            "port_count": len(per_port),
            "adapter_count": total_adapters,
            "status_counts": dict(total_status),
            "total_enosys_returns": total_enosys,
        },
    }


def render_md(report: Dict[str, Any]) -> str:
    s = report["summary"]
    lines: List[str] = []
    lines.append("# HAL Port Maturity Report")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_hal_maturity_report.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"- Ports: {int(s.get('port_count', 0))}")
    lines.append(f"- HAL adapters: {int(s.get('adapter_count', 0))}")
    counts = s.get("status_counts", {})
    lines.append(f"- Real adapters: {int(counts.get('real', 0))}")
    lines.append(f"- Real adapters with optional `-ENOSYS` gaps: {int(counts.get('real_with_optional_gaps', 0))}")
    lines.append(f"- Contract-only adapters: {int(counts.get('contract_only', 0))}")
    lines.append(f"- Total `return -ENOSYS;` sites: {int(s.get('total_enosys_returns', 0))}")
    lines.append("")
    lines.append("## Per-Port Snapshot")
    lines.append("| Port | Adapters | Real | Real+gaps | Contract-only | `-ENOSYS` sites |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for row in report.get("ports", []):
        counts = row.get("status_counts", {})
        lines.append(
            f"| {row.get('port','')} | {int(row.get('adapter_count', 0))} | "
            f"{int(counts.get('real', 0))} | {int(counts.get('real_with_optional_gaps', 0))} | "
            f"{int(counts.get('contract_only', 0))} | {int(row.get('total_enosys', 0))} |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate HAL port maturity report artifacts.")
    ap.add_argument("--json-out", required=True, type=Path)
    ap.add_argument("--md-out", required=True, type=Path)
    args = ap.parse_args()

    root = Path(__file__).resolve().parents[1]
    report = build_report(root)

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    args.md_out.parent.mkdir(parents=True, exist_ok=True)
    args.json_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    args.md_out.write_text(render_md(report), encoding="utf-8")

    summary = report["summary"]
    print(f"[hal-maturity] ports: {summary['port_count']}")
    print(f"[hal-maturity] adapters: {summary['adapter_count']}")
    print(f"[hal-maturity] enosys sites: {summary['total_enosys_returns']}")
    print(f"[hal-maturity] wrote: {args.json_out}")
    print(f"[hal-maturity] wrote: {args.md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
