#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List


def build_payload(root: Path) -> Dict[str, object]:
    rows: List[Dict[str, str]] = []
    for src in sorted((root / "basalt_hal" / "ports").glob("*/hal_*.c")):
        text = src.read_text(encoding="utf-8")
        if "BASALT_HAL_UNSUPPORTED_STUB" not in text:
            continue
        port = src.parent.name
        primitive = src.stem.replace("hal_", "", 1)
        rows.append({"port": port, "primitive": primitive, "path": str(src.relative_to(root))})

    by_port: Dict[str, List[str]] = {}
    for r in rows:
        by_port.setdefault(r["port"], []).append(r["primitive"])
    for port in list(by_port.keys()):
        by_port[port] = sorted(by_port[port])

    return {
        "version": "1.0.0",
        "generator": "tools/generate_hal_unsupported_stub_inventory.py",
        "summary": {
            "stub_file_count": len(rows),
            "port_count_with_stubs": len(by_port),
        },
        "rows": rows,
        "by_port": by_port,
    }


def write_md(payload: Dict[str, object], out: Path) -> None:
    rows = payload.get("rows", [])
    by_port = payload.get("by_port", {})
    summary = payload.get("summary", {})

    lines: List[str] = []
    lines.append("# HAL Unsupported Stub Inventory v1")
    lines.append("")
    lines.append("Auto-generated by `tools/generate_hal_unsupported_stub_inventory.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Unsupported stub files: {summary.get('stub_file_count', 0)}")
    lines.append(f"- Ports with unsupported stubs: {summary.get('port_count_with_stubs', 0)}")
    lines.append("")
    lines.append("## By Port")
    lines.append("")
    for port in sorted(by_port.keys()):
        prims = ", ".join(by_port[port]) if by_port[port] else "-"
        lines.append(f"- {port}: {prims}")
    lines.append("")
    lines.append("## Files")
    lines.append("")
    lines.append("| Port | Primitive | Path |")
    lines.append("|---|---|---|")
    for row in rows:
        lines.append(f"| {row['port']} | {row['primitive']} | {row['path']} |")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate HAL unsupported-stub inventory artifacts.")
    ap.add_argument("--json-out", default="docs/planning/HAL_UNSUPPORTED_STUB_INVENTORY.json")
    ap.add_argument("--md-out", default="docs/planning/HAL_UNSUPPORTED_STUB_INVENTORY.md")
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    payload = build_payload(root)

    json_out = (root / args.json_out).resolve()
    md_out = (root / args.md_out).resolve()
    json_out.parent.mkdir(parents=True, exist_ok=True)

    json_out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    write_md(payload, md_out)

    print(f"[hal-stubs] files: {payload['summary']['stub_file_count']}")
    print(f"[hal-stubs] ports: {payload['summary']['port_count_with_stubs']}")
    print(f"[hal-stubs] wrote: {json_out}")
    print(f"[hal-stubs] wrote: {md_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
