#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash tools/pic16_curiosity_nano_run.sh [options]

Options:
  --source <file>         C source file to compile (default: autogenerated blink source)
  --workdir <dir>         Build/output directory (default: /tmp/pic16_curiosity_run)
  --chip <name>           Target MCU name for XC8 -mcpu (default: 16F13145)
  --dfp-version <ver>     PIC16F1xxxx DFP version (default: 1.29.444)
  --hex-name <name.hex>   Output HEX filename (default: main.hex)
  --label <disk-label>    Curiosity mass-storage label (default: CURIOSITY)
  --no-flash              Compile only; skip drag-and-drop flash
  -h, --help              Show this help

Environment overrides:
  XC8_HOME                Default: $HOME/opt/microchip/xc8/v3.10
  PACK_BASE               Default: $HOME/opt/microchip/packs
EOF
}

SOURCE=""
WORKDIR="/tmp/pic16_curiosity_run"
CHIP="16F13145"
DFP_VERSION="1.29.444"
HEX_NAME="main.hex"
LABEL="CURIOSITY"
NO_FLASH=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source) SOURCE="${2:?missing value}"; shift 2 ;;
    --workdir) WORKDIR="${2:?missing value}"; shift 2 ;;
    --chip) CHIP="${2:?missing value}"; shift 2 ;;
    --dfp-version) DFP_VERSION="${2:?missing value}"; shift 2 ;;
    --hex-name) HEX_NAME="${2:?missing value}"; shift 2 ;;
    --label) LABEL="${2:?missing value}"; shift 2 ;;
    --no-flash) NO_FLASH=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage; exit 2 ;;
  esac
done

XC8_HOME="${XC8_HOME:-$HOME/opt/microchip/xc8/v3.10}"
PACK_BASE="${PACK_BASE:-$HOME/opt/microchip/packs}"
DFP_DIR="$PACK_BASE/Microchip/PIC16F1xxxx_DFP/$DFP_VERSION/xc8"

mkdir -p "$WORKDIR"

if [[ -z "$SOURCE" ]]; then
  SOURCE="$WORKDIR/main.c"
  cat >"$SOURCE" <<'EOF'
#include <xc.h>

void main(void) {
    TRISA = 0x00;
    LATA = 0x00;
    while (1) {
        LATA ^= 0x01;
        for (volatile unsigned long i = 0; i < 50000UL; ++i) {
            NOP();
        }
    }
}
EOF
fi

if [[ ! -x "$XC8_HOME/bin/xc8-cc" ]]; then
  echo "Missing XC8 compiler at: $XC8_HOME/bin/xc8-cc" >&2
  exit 1
fi

if [[ ! -d "$DFP_DIR" ]]; then
  echo "Missing DFP dir: $DFP_DIR" >&2
  echo "Install Microchip.PIC16F1xxxx_DFP.$DFP_VERSION.atpack under $PACK_BASE" >&2
  exit 1
fi

export PATH="$XC8_HOME/bin:$XC8_HOME/pic-as/bin:$PATH"

BASE="${HEX_NAME%.hex}"
OUT_ELF="$WORKDIR/$BASE.elf"
OUT_HEX="$WORKDIR/$BASE.hex"
BUILD_LOG="$WORKDIR/build.log"

echo "[pic16] Compiling $SOURCE"
xc8-cc -mcpu="$CHIP" -mdfp="$DFP_DIR" -mdebugger=none -O0 -o "$OUT_ELF" "$SOURCE" >"$BUILD_LOG" 2>&1
cat "$BUILD_LOG"

if [[ ! -f "$OUT_HEX" ]]; then
  echo "Expected HEX not produced: $OUT_HEX" >&2
  exit 1
fi

echo "[pic16] Build OK: $OUT_HEX"

if [[ "$NO_FLASH" -eq 1 ]]; then
  echo "[pic16] --no-flash set; skipping drag-and-drop"
  exit 0
fi

if ! command -v udisksctl >/dev/null 2>&1; then
  echo "udisksctl not found; cannot auto-mount Curiosity drive" >&2
  exit 1
fi

DEV="$(lsblk -pnro NAME,LABEL,TYPE | awk -v label="$LABEL" '$3=="disk" && $2==label {print $1; exit}')"
if [[ -z "$DEV" ]]; then
  echo "No disk found with label '$LABEL' (is Curiosity Nano connected?)" >&2
  exit 1
fi

MOUNT_LOG="$WORKDIR/mount.log"
echo "[pic16] Mounting $DEV"
udisksctl mount -b "$DEV" >"$MOUNT_LOG"
cat "$MOUNT_LOG"
MP="$(awk -F'at ' '/Mounted/ {print $2}' "$MOUNT_LOG" | sed 's/\.$//')"

if [[ -z "$MP" || ! -d "$MP" ]]; then
  echo "Failed to detect mount point from: $MOUNT_LOG" >&2
  exit 1
fi

echo "[pic16] Copying HEX to $MP"
cp "$OUT_HEX" "$MP/"
sync
sleep 1

if [[ -f "$MP/STATUS.TXT" ]]; then
  echo "[pic16] STATUS.TXT:"
  sed -n '1,120p' "$MP/STATUS.TXT"
fi

echo "[pic16] Unmounting $DEV"
udisksctl unmount -b "$DEV" >/dev/null
echo "[pic16] Flash step complete. Re-open STATUS.TXT after remount for post-program status."
