#!/usr/bin/env python3
"""
PIC16 codegen backend for BasaltOS configurator.
Generates a minimal XC8-friendly project scaffold.
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional


def _mkdir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _define_from_pin(name: str, value) -> str:
    if value is None:
        return f"// {name} not set"
    return f"#define {name} {value}"


def _emit_basalt_config_h(
    out_path: Path,
    board_id: str,
    target_id: str,
    enabled_modules: List[str],
    pins: Dict[str, str],
    module_config: Optional[dict] = None,
    clock: Optional[dict] = None,
    fuses: Optional[dict] = None,
) -> None:
    lines: List[str] = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("// Generated by BasaltOS configurator (PIC16 target)")
    lines.append(f"#define BASALT_TARGET_{target_id.upper()} 1")
    lines.append(f"#define BASALT_BOARD_ID \"{board_id}\"")

    if clock:
        lines.append(f"#define BASALT_CLOCK_SOURCE \"{clock.get('source', 'HS')}\"")
        lines.append(f"#define BASALT_CLOCK_HZ {int(clock.get('freq_hz', 20000000))}")

    if fuses:
        for k, v in fuses.items():
            macro = f"BASALT_FUSE_{str(k).upper()}"
            lines.append(f"#define {macro} {1 if v else 0}")

    lines.append("")
    lines.append("// Enabled modules")
    for mid in sorted(enabled_modules):
        macro = f"BASALT_ENABLE_{mid.upper()}"
        lines.append(f"#define {macro} 1")

    lines.append("")
    lines.append("// Pin mappings")
    for key, val in pins.items():
        macro = f"BASALT_PIN_{key.upper()}"
        lines.append(_define_from_pin(macro, val))

    if module_config:
        lines.append("")
        lines.append("// Module configuration")
        for module_id, options in module_config.items():
            if not isinstance(options, dict):
                continue
            for key, val in options.items():
                macro = f"BASALT_CFG_{str(module_id).upper()}_{str(key).upper()}"
                if isinstance(val, bool):
                    lines.append(f"#define {macro} {1 if val else 0}")
                elif isinstance(val, (int, float)) and int(val) == val:
                    lines.append(f"#define {macro} {int(val)}")
                else:
                    lines.append(f"#define {macro} \"{val}\"")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _emit_main_c(out_path: Path) -> None:
    out_path.write_text(
        """#include <xc.h>
#include "basalt_config.h"

void mcu_init(void);
void app_init(void);
void app_loop(void);

int main(void) {
    mcu_init();
    app_init();
    while (1) {
        app_loop();
    }
    return 0;
}
""",
        encoding="utf-8",
    )


def _emit_mcu_init(out_path: Path, clock: Optional[dict], fuses: Optional[dict]) -> None:
    source = clock.get("source", "HS") if clock else "HS"
    freq = int(clock.get("freq_hz", 20000000)) if clock else 20000000
    wdt = fuses.get("wdt", False) if fuses else False
    bor = fuses.get("bor", True) if fuses else True
    lvp = fuses.get("lvp", False) if fuses else False
    mclr = fuses.get("mclr", True) if fuses else True
    cpd = fuses.get("cpd", False) if fuses else False
    cp = fuses.get("cp", False) if fuses else False

    out_path.write_text(
        (
            "#include <xc.h>\n"
            "#include \"basalt_config.h\"\n"
            "\n"
            f"#pragma config FOSC = {source}\n"
            f"#pragma config WDT = {'ON' if wdt else 'OFF'}\n"
            f"#pragma config BOREN = {'ON' if bor else 'OFF'}\n"
            f"#pragma config LVP = {'ON' if lvp else 'OFF'}\n"
            f"#pragma config MCLRE = {'ON' if mclr else 'OFF'}\n"
            f"#pragma config CPD = {'ON' if cpd else 'OFF'}\n"
            f"#pragma config CP = {'ON' if cp else 'OFF'}\n"
            "\n"
            f"#define _XTAL_FREQ {freq}\n"
            "\n"
            "void mcu_init(void) {\n"
            "    // TODO: configure oscillator, port directions, and peripherals\n"
            "}\n"
        ),
        encoding="utf-8",
    )


def _emit_interrupts(out_path: Path) -> None:
    out_path.write_text(
        """#include <xc.h>

void __interrupt() isr(void) {
    // TODO: dispatch interrupts
}
""",
        encoding="utf-8",
    )


def _emit_stub(out_path: Path, title: str) -> None:
    out_path.write_text(
        f"// {title}\n// TODO: implement\n",
        encoding="utf-8",
    )


def generate_pic16_project(
    out_dir: Path,
    board_id: str,
    target_id: str,
    enabled_modules: List[str],
    pins: Dict[str, str],
    module_config: Optional[dict] = None,
    clock: Optional[dict] = None,
    fuses: Optional[dict] = None,
    has_interrupts: bool = True,
) -> Dict[str, str]:
    include_dir = out_dir / "include"
    src_dir = out_dir / "src"
    drivers_dir = src_dir / "drivers"
    apps_dir = src_dir / "apps"

    _mkdir(include_dir)
    _mkdir(src_dir)
    _mkdir(drivers_dir)
    _mkdir(apps_dir)

    basalt_h = include_dir / "basalt_config.h"
    _emit_basalt_config_h(
        basalt_h,
        board_id=board_id,
        target_id=target_id,
        enabled_modules=enabled_modules,
        pins=pins,
        module_config=module_config,
        clock=clock,
        fuses=fuses,
    )

    _emit_main_c(src_dir / "main.c")
    _emit_mcu_init(src_dir / "mcu_init.c", clock=clock, fuses=fuses)
    if has_interrupts:
        _emit_interrupts(src_dir / "interrupts.c")

    module_to_driver = {
        "gpio": "gpio.c",
        "uart": "uart.c",
        "i2c": "i2c_hw.c",
        "spi": "spi.c",
        "adc": "adc.c",
        "eeprom": "eeprom.c",
        "timer": "timer.c",
        "remote_node": "remote_node.c",
    }

    for mid, filename in module_to_driver.items():
        if mid in enabled_modules:
            _emit_stub(drivers_dir / filename, f"Driver stub for {mid}")

    readme = out_dir / "README.md"
    readme.write_text(
        """# BasaltOS PIC16 Project

Generated by the BasaltOS configurator.

## Build
Open in MPLAB X or compile with XC8.
""",
        encoding="utf-8",
    )

    return {
        "basalt_config.h": str(basalt_h),
        "main.c": str(src_dir / "main.c"),
        "mcu_init.c": str(src_dir / "mcu_init.c"),
        "interrupts.c": str(src_dir / "interrupts.c") if has_interrupts else "",
        "drivers_dir": str(drivers_dir),
        "apps_dir": str(apps_dir),
        "README.md": str(readme),
    }


def render_basalt_config_preview(
    board_id: str,
    target_id: str,
    enabled_modules: List[str],
    pins: Dict[str, str],
    module_config: Optional[dict] = None,
    clock: Optional[dict] = None,
    fuses: Optional[dict] = None,
) -> str:
    tmp = Path("/tmp") / "basalt_pic16_preview.h"
    _emit_basalt_config_h(
        tmp,
        board_id=board_id,
        target_id=target_id,
        enabled_modules=enabled_modules,
        pins=pins,
        module_config=module_config,
        clock=clock,
        fuses=fuses,
    )
    return tmp.read_text(encoding="utf-8")
