#!/usr/bin/env python3
"""
Generate a PlatformIO phase-1 starter project from BasaltOS configure output.

Input contract:
- config/generated/basalt.features.json
- config/generated/sdkconfig.defaults (optional but recommended)

Output (default):
- tmp/platformio_phase1/platformio.ini
- tmp/platformio_phase1/README.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def detect_pio_board(board_id: str, board_dir: str) -> str:
    b = (board_id or "").lower()
    d = (board_dir or "").lower()
    s = f"{b} {d}"
    if "c3" in s:
        return "esp32-c3-devkitm-1"
    if "s3" in s:
        return "esp32-s3-devkitc-1"
    return "esp32dev"


def main() -> int:
    ap = argparse.ArgumentParser(description="Bootstrap PlatformIO phase-1 config from basalt.features.json")
    ap.add_argument("--features", default="config/generated/basalt.features.json", help="Path to basalt.features.json")
    ap.add_argument("--sdk-defaults", default="config/generated/sdkconfig.defaults", help="Path to sdkconfig.defaults")
    ap.add_argument("--outdir", default="tmp/platformio_phase1", help="Output directory")
    ap.add_argument("--pio-board", default=None, help="Override PlatformIO board id")
    args = ap.parse_args()

    features_path = Path(args.features)
    if not features_path.exists():
        raise SystemExit(f"Missing features file: {features_path}")

    data = json.loads(features_path.read_text(encoding="utf-8"))
    platform = str(data.get("platform", "")).strip().lower()
    board_id = str(data.get("board_id", "")).strip()
    board_dir = str(data.get("board_dir", "")).strip()
    drivers = data.get("drivers") or []

    if platform != "esp32":
        raise SystemExit(
            f"Phase-1 bootstrap currently supports platform=esp32 only (got: {platform or '<empty>'})."
        )

    pio_board = args.pio_board or detect_pio_board(board_id, board_dir)
    sdk_defaults = Path(args.sdk_defaults)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    platformio_ini = outdir / "platformio.ini"
    readme = outdir / "README.md"

    ini_lines = [
        "; Auto-generated by tools/platformio/bootstrap_from_features.py",
        "[env:basaltos_phase1]",
        "platform = espressif32",
        f"board = {pio_board}",
        "framework = espidf",
        "monitor_speed = 115200",
        "build_flags =",
        "  -I../../config/generated",
    ]

    if sdk_defaults.exists():
        ini_lines += [
            "board_build.sdkconfig_defaults =",
            f"  ../../{sdk_defaults.as_posix()}",
        ]

    platformio_ini.write_text("\n".join(ini_lines) + "\n", encoding="utf-8")

    readme_lines = [
        "# BasaltOS PlatformIO Phase-1 Bootstrap",
        "",
        "Generated from BasaltOS configure outputs.",
        "",
        "## Source Inputs",
        f"- `{features_path.as_posix()}`",
        f"- `{sdk_defaults.as_posix()}`" if sdk_defaults.exists() else "- sdkconfig.defaults not found (optional)",
        "",
        "## Selected Values",
        f"- platform: `{platform}`",
        f"- board_id: `{board_id or '-'}`",
        f"- board_dir: `{board_dir or '-'}`",
        f"- inferred pio board: `{pio_board}`",
        f"- enabled drivers: `{', '.join(drivers) if drivers else '(none)'}`",
        "",
        "## Build",
        "From this output directory:",
        "```bash",
        "pio run",
        "```",
        "",
        "## Notes",
        "- This is a phase-1 bootstrap for contract validation, not a full PlatformIO platform package.",
        "- Board id inference is heuristic; pass `--pio-board` for exact control.",
    ]
    readme.write_text("\n".join(readme_lines) + "\n", encoding="utf-8")

    print(platformio_ini)
    print(readme)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
